[phases.setup]
nixPkgs = ["python311Full", "gcc", "dejavu_fonts", "fontconfig"]
aptPkgs = ["fonts-dejavu-core", "fonts-dejavu-extra"]

[phases.install]
cmds = ["pip install -r requirements.txt", "fc-cache -f -v || true"]

[start]
cmd = "gunicorn app:app --timeout 120"
